-- AlterTable
ALTER TABLE "Customers" ADD COLUMN     "BankAccountName" VARCHAR(150),
ADD COLUMN     "BankAccountNumber" VARCHAR(50),
ADD COLUMN     "BankName" VARCHAR(100),
ADD COLUMN     "ContactPerson" VARCHAR(255),
ADD COLUMN     "Country" VARCHAR(100),
ADD COLUMN     "CreditDayLimit" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "DiscountType" VARCHAR(30) NOT NULL DEFAULT 'ITEM_LIST',
ADD COLUMN     "Fax" VARCHAR(50),
ADD COLUMN     "MaxCreditAmount" DECIMAL(15,2) NOT NULL DEFAULT 0,
ADD COLUMN     "PostalCode" VARCHAR(20),
ADD COLUMN     "Province" VARCHAR(100),
ADD COLUMN     "SalesPersonID" INTEGER,
ADD COLUMN     "TaxAddress" VARCHAR(500),
ADD COLUMN     "TaxMode" VARCHAR(20) NOT NULL DEFAULT 'DEFAULT',
ADD COLUMN     "TaxNIK" VARCHAR(50),
ADD COLUMN     "TaxName" VARCHAR(255),
ADD COLUMN     "TaxRate" DECIMAL(5,2) NOT NULL DEFAULT 0,
ADD COLUMN     "TaxValueSource" VARCHAR(20) NOT NULL DEFAULT 'DEFAULT';

-- AlterTable
ALTER TABLE "SalesPersons" ADD COLUMN     "BankAccountName" VARCHAR(150),
ADD COLUMN     "BankAccountNumber" VARCHAR(50),
ADD COLUMN     "BankName" VARCHAR(100),
ADD COLUMN     "City" VARCHAR(100),
ADD COLUMN     "CommissionNominal" DECIMAL(15,2) NOT NULL DEFAULT 0,
ADD COLUMN     "CommissionPercent" DECIMAL(7,2) NOT NULL DEFAULT 0,
ADD COLUMN     "CommissionSystem" VARCHAR(20) NOT NULL DEFAULT 'NONE',
ADD COLUMN     "CommissionTiers" JSONB,
ADD COLUMN     "CommissionType" VARCHAR(20) NOT NULL DEFAULT 'PERCENT',
ADD COLUMN     "ContactPerson" VARCHAR(255),
ADD COLUMN     "Country" VARCHAR(100),
ADD COLUMN     "Fax" VARCHAR(50),
ADD COLUMN     "Notes" VARCHAR(1000),
ADD COLUMN     "PostalCode" VARCHAR(20),
ADD COLUMN     "Province" VARCHAR(100),
ADD COLUMN     "TaxID" VARCHAR(50);

-- AlterTable
ALTER TABLE "Suppliers" ADD COLUMN     "Country" VARCHAR(100),
ADD COLUMN     "Fax" VARCHAR(50),
ADD COLUMN     "PostalCode" VARCHAR(20),
ADD COLUMN     "TaxMode" VARCHAR(20) NOT NULL DEFAULT 'DEFAULT',
ADD COLUMN     "TaxRate" DECIMAL(5,2) NOT NULL DEFAULT 0,
ADD COLUMN     "TaxValueSource" VARCHAR(20) NOT NULL DEFAULT 'DEFAULT';

-- AddForeignKey
ALTER TABLE "Customers" ADD CONSTRAINT "Customers_SalesPersonID_fkey" FOREIGN KEY ("SalesPersonID") REFERENCES "SalesPersons"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

